/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chest.glb --T -o src/components/models/chest.jsx 
Files: public/models/chest.glb [2.29MB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\chest-transformed.glb [347.94KB] (85%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Chest(props) {
  const { nodes, materials } = useGLTF('public/models/chest-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.007]} rotation={[-Math.PI / 2, 0, 0]} scale={0.667}>
        <mesh geometry={nodes.Object_58004.geometry} material={materials['Metal_Base.005']} />
        <mesh geometry={nodes.Object_58004_1.geometry} material={materials['Chapa_Meta.005']} />
        <mesh geometry={nodes.Object_58004_2.geometry} material={materials['Madera_cofre.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('public/models/chest-transformed.glb')
