/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/unoptimised/dressing.glb --T --s --o src/components/models/dressing.jsx 
Files: public/models/unoptimised/dressing.glb [5.07KB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\dressing-transformed.glb [1.65KB] (67%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Dressing(props) {
  const { nodes, materials } = useGLTF('public/models/dressing-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} material-roughness="1" material-metalness="0"/>
    </group>
  )
}

useGLTF.preload('public/models/dressing-transformed.glb')
