/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/flag.glb --T -o src/components/models/flag.jsx 
Files: public/models/flag.glb [77.16KB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\flag-transformed.glb [7.16KB] (91%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Flag(props) {
  const { nodes, materials } = useGLTF('public/models/flag-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.25]}>
        <mesh geometry={nodes.Cylinder_Abu2_0003.geometry} material={materials['Abu2.003']} />
        <mesh geometry={nodes.Cylinder_Abu2_0003_1.geometry} material={materials['Putih.003']} />
        <mesh geometry={nodes.Cylinder_Abu2_0003_2.geometry} material={materials['Merah.003']} />
      </group>
    </group>
  )
}

useGLTF.preload('public/models/flag-transformed.glb')
