/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/unoptimised/floor.glb --o src/components/models/floor.jsx --transform --s 
Files: public/models/unoptimised/floor.glb [1.95MB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\floor-transformed.glb [9.12KB] (100%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import {RigidBody} from "@react-three/rapier";

export function Floor(props) {
  const { nodes, materials } = useGLTF('models/floor-transformed.glb')
  return (
    <group {...props} dispose={null}>
        <RigidBody type={"fixed"} colliders={"cuboid"}>
            <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 5]} material-roughness="1" />
        </RigidBody>
    </group>
  )
}

useGLTF.preload('models/floor-transformed.glb')
