/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pillar_debris.glb --T -o src/components/models/pillar_debris.jsx 
Files: public/models/pillar_debris.glb [13.07MB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\pillar_debris-transformed.glb [985.23KB] (92%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pillar_debris(props) {
  const { nodes, materials } = useGLTF('models/pillar_debris-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_7.geometry} material={materials['Columna_Material.002']} position={[-0.599, 2.782, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.667} />
    </group>
  )
}

useGLTF.preload('models/pillar_debris-transformed.glb')
