/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/pillar.glb --T -o src/components/models/pillar.jsx 
Files: public/models/pillar.glb [23.24MB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\pillar-transformed.glb [1.48MB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Pillar(props) {
  const { nodes, materials } = useGLTF('models/pillar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.Object_32.geometry} material={materials.Columna_Material} position={[0, 3.299, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('models/pillar-transformed.glb')
