/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/podium.glb --T -o src/components/models/podium.jsx 
Files: public/models/podium.glb [955.67KB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\podium-transformed.glb [229KB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Podium(props) {
  const { nodes, materials } = useGLTF('models/podium-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow geometry={nodes.PodiumLarge_PodiumLarge_Material_0.geometry} material={materials['Suelo_Bueno.001']} position={[0, 1.328, -0.326]} rotation={[-Math.PI / 2, 0, 0]} scale={[19.208, 16.483, 0.358]} />
    </group>
  )
}

useGLTF.preload('models/podium-transformed.glb')
