/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stick.gltf --T -o src/components/models/stick.jsx 
Files: public/models/stick.gltf [2.33KB] > C:\Dokumentumok\.Uni\.zs2024\BP\code\r3f\src\components\models\stick-transformed.glb [1.89KB] (19%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Stick(props) {
  const { nodes, materials } = useGLTF('models/stick-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Stick_Material_0.geometry} material={materials['Material.001']} position={[0, 0.526, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.004, 0.005, 0.004]} />
    </group>
  )
}

useGLTF.preload('models/stick-transformed.glb')
